const products=[
 {id:1,name:'ポータブル テーブルライト',category:'home',label:'暮らし',price:'¥8,800',desc:'触れるだけで明るさを調整できる、充電式のテーブルライト。寝室にも食卓にも静かになじみます。',image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=85'},
 {id:2,name:'バランシング フェイスオイル',category:'beauty',label:'美容',price:'¥3,960',desc:'植物由来のオイルを軽やかにブレンド。乾燥しやすい肌をやさしく包み、自然なつやを与えます。',image:'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1000&q=85'},
 {id:3,name:'クラフトグラノーラ',category:'food',label:'食品',price:'¥1,280',desc:'香ばしいオーツ麦とナッツ、季節のドライフルーツ。毎朝食べたくなる、甘さ控えめの味わいです。',image:'https://images.unsplash.com/photo-1517093157656-b9eccef91cb1?auto=format&fit=crop&w=1000&q=85'},
 {id:4,name:'キャンバス トート',category:'fashion',label:'ファッション',price:'¥5,500',desc:'丈夫な帆布を使い、肩にかけやすい長さに整えました。荷物が多い日にも頼れる定番バッグです。',image:'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=85'},
 {id:5,name:'ハンドドリップ ケトル',category:'home',label:'暮らし',price:'¥7,480',desc:'狙った場所へ静かに注げる細口ノズル。朝のコーヒー時間を、少しだけ丁寧にする道具です。',image:'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=1200&q=85'},
 {id:6,name:'ハーバル バスソルト',category:'beauty',label:'美容',price:'¥2,420',desc:'海塩と天然精油を合わせた入浴料。深呼吸したくなる香りで、一日の終わりを心地よく整えます。',image:'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1000&q=85'},
 {id:7,name:'瀬戸内レモンシロップ',category:'food',label:'食品',price:'¥1,650',desc:'瀬戸内産レモンを皮ごと使った、爽やかなシロップ。炭酸水や紅茶でお楽しみください。',image:'https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=1000&q=85'},
 {id:8,name:'オーガニック コットンT',category:'fashion',label:'ファッション',price:'¥4,290',desc:'やわらかな肌触りと、身体の線を拾いすぎない形。毎日選びたくなる一枚を目指しました。',image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1000&q=85'}
];
let current='all';let saved=JSON.parse(localStorage.getItem('maru-saved')||'[]');
const grid=document.querySelector('#productGrid'),count=document.querySelector('#resultCount'),search=document.querySelector('#searchInput');
function render(){const q=search.value.trim().toLowerCase();const items=products.filter(p=>(current==='all'||p.category===current)&&p.name.toLowerCase().includes(q));grid.innerHTML=items.map(p=>`<article class="product-card"><div class="product-image" style="background-image:url('${p.image}')"><button class="save ${saved.includes(p.id)?'active':''}" data-save="${p.id}" aria-label="${p.name}をお気に入りに追加">${saved.includes(p.id)?'♥':'♡'}</button></div><div class="product-info"><h3>${p.name}</h3><p>${p.label}</p><strong>${p.price}</strong></div><button class="card-open" data-open="${p.id}" aria-label="${p.name}の詳細を見る"></button></article>`).join('');count.textContent=`${items.length} items`;document.querySelector('#emptyState').hidden=items.length!==0;updateSaved();}
function toggleSave(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem('maru-saved',JSON.stringify(saved));render();}
function updateSaved(){document.querySelector('#savedCount').textContent=saved.length;const items=products.filter(p=>saved.includes(p.id));document.querySelector('#savedList').innerHTML=items.length?items.map(p=>`<div class="saved-item"><div class="saved-item-img" style="background-image:url('${p.image}')"></div><div><h3>${p.name}</h3><p>${p.price}</p></div><button data-remove="${p.id}" aria-label="削除">×</button></div>`).join(''):'<p style="color:var(--muted)">気になる商品を♡で保存できます。</p>';}
document.addEventListener('click',e=>{const saveBtn=e.target.closest('[data-save]');if(saveBtn){toggleSave(+saveBtn.dataset.save);return}const open=e.target.closest('[data-open]');if(open){const p=products.find(x=>x.id===+open.dataset.open);document.querySelector('#dialogContent').innerHTML=`<div class="dialog-inner"><div class="dialog-image" style="background-image:url('${p.image}')"></div><div class="dialog-copy"><p class="category">${p.label}</p><h2>${p.name}</h2><p class="price">${p.price}</p><p class="description">${p.desc}</p><button data-save="${p.id}">${saved.includes(p.id)?'お気に入りから外す':'お気に入りに追加'}</button></div></div>`;document.querySelector('#productDialog').showModal()}const remove=e.target.closest('[data-remove]');if(remove)toggleSave(+remove.dataset.remove)});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');current=b.dataset.filter;render()}));search.addEventListener('input',render);document.querySelector('#resetButton').addEventListener('click',()=>{search.value='';current='all';document.querySelector('.filter.active').classList.remove('active');document.querySelector('[data-filter="all"]').classList.add('active');render()});
const panel=document.querySelector('#savedPanel'),overlay=document.querySelector('#overlay');function closePanel(){panel.classList.remove('open');panel.setAttribute('aria-hidden','true');overlay.hidden=true}document.querySelector('#savedButton').onclick=()=>{panel.classList.add('open');panel.setAttribute('aria-hidden','false');overlay.hidden=false};document.querySelector('#closeSaved').onclick=closePanel;overlay.onclick=closePanel;document.querySelector('.dialog-close').onclick=()=>document.querySelector('#productDialog').close();render();
